export const architectureRules = {
  fileSize: {
    hardLimit: 500,
    softLimit: 300,
  },
  splitDomains: ["runtime", "operations", "persistence", "react", "sync"],
  valueDependencies: {
    aspects: [],
    browser: [],
    collaboration: [],
    commands: ["history", "hotkeys"],
    constraints: [],
    entities: [],
    history: [],
    hotkeys: [],
    index: [
      "aspects",
      "browser",
      "commands",
      "collaboration",
      "constraints",
      "entities",
      "history",
      "hotkeys",
      "indexes",
      "interaction",
      "json",
      "operations",
      "persistence",
      "patches",
      "plugins",
      "runtime",
      "selection",
      "serialization",
      "share",
      "testing",
      "tree",
      "viewport",
    ],
    indexes: [],
    interaction: ["operations"],
    json: [],
    operations: ["commands", "history", "runtime", "serialization", "json"],
    patches: ["json"],
    persistence: ["runtime"],
    plugins: ["commands"],
    react: ["browser", "commands", "hotkeys", "persistence", "runtime", "tree"],
    runtime: ["aspects", "commands", "history"],
    selection: [],
    serialization: ["json"],
    share: [],
    sync: ["collaboration", "operations", "persistence", "runtime"],
    testing: ["json", "operations", "serialization"],
    tree: [],
    viewport: [],
  },
};
